#ifndef __fr_charlotte_libreofficewakatime_libreofficewakatimeextension_idl__
#define __fr_charlotte_libreofficewakatime_libreofficewakatimeextension_idl__

#include <fr/charlotte/libreofficewakatime/XLibreOfficeWakatimeExtension.idl>
module fr { module charlotte { module libreofficewakatime { 	

	service LibreOfficeWakatimeExtension : fr::charlotte::libreofficewakatime::XLibreOfficeWakatimeExtension {

	};

 }; }; };
#endif
