#ifndef __fr_charlotte_libreofficewakatime_libreofficewakatimeextension_idl__
#define __fr_charlotte_libreofficewakatime_libreofficewakatimeextension_idl__

#include <com/sun/star/task/XJobExecutor.idl>
module fr { module charlotte { module libreofficewakatime { 	

	service LibreOfficeWakatimeExtension : com::sun::star::task::XJobExecutor {

	};

 }; }; };
#endif
